title: Filmhub
description: Film distribution marketplace for indie filmmakers and video streaming services
# Boolean variables stopped working, so: set to false by commenting out
# social: false
# offline: false
url: http://filmhub.com
permalink: none
plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag
sass:
  # style: compressed
  sourcemap: inline
  # debug_info: true
  line_numbers: true
  line_comments: true
kramdown:
  auto_ids: true

# jekyll-seo-tag properties
twitter:
  username: filmhubhq
facebook:
  app_id: 159020761463817
  publisher: https://www.facebook.com/filmhubhq
  admins: 1034572123
logo: /images/icon_v2_600.png
social:
  name: Filmhub
  links:
    - https://twitter.com/filmhubhq
    - https://www.facebook.com/filmhubhq
    - https://www.linkedin.com/company/filmhub/
    - https://www.youtube.com/user/kinonationfilms
author:
  twitter: filmhubhq

defaults:
  -
    scope:
      path: oldblog
    values:
      sitemap: false
  -
    scope:
      path: modals
    values:
      sitemap: false
  -
    scope:
      path: help
    values:
      sitemap: false
